# Site settings
title: IT & Stuff by Masa331
email: pdonat@seznam.cz
description: > # this means to ignore newlines until "baseurl:"
  Masa331 blogging about technology things and other stuff. Have a good one!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://masa331.github.io" # the base hostname & protocol for your site
twitter_username: DonatP
github_username:  Masa331

# Build settings
gems: [jekyll_github_sample]
